### ISSUE TITLE
Not completely respecting screen DPI setting?

### ISSUE THREAD

**Issue by lowenthalm** [LucCoiffier/DSS#19]
I am running Windows 7 (all the latest service packs installed) under Parallels on a Mac Book Pro with a retina display which has a roughly 150dpi screen.

Certain elements appear to be half scale. The text in the command tab on the left is the correct size, but the width of the tab is about half the width it needs to be, truncating the right half of all the text in this tab. In addition, the file list tab, the text "Main Group" is half the size you would expect. All the rest of the text in the file list tab looks to be the correct size. Resizing the window does not correct any of this and the width of the command tab can not be adjusted. 

In addition icons and triangular slider controls all appear to be half the size they should be, but are framed in a frame that appears to be the correct size. This is also the case in the RGB panel of the processing tab.

**Comment by perdrix52** [comment]
This is already fixed

 

Dave

**Comment by perdrix52** [comment]
Already fixed
