### ISSUE TITLE
Problem with incorrect window display after minimise restore

### ISSUE THREAD

**Issue by perdrix52** [LucCoiffier/DSS#23]
To reproduce, load enough lights for scroll bars to be required in the file list.

Grab the resizing bar above the file list and move upward to reduce the image area.

Minimise DSS, and then restore.  The image area comes back larger than before the minimise and the bottom of the file list with the group tabs is gone.  The scroll bars may also be gone or incomplete.

Before minimise:
![image](https://user-images.githubusercontent.com/20211762/39160204-e2082bca-4761-11e8-8ebe-63ab171fd71b.png)

After restore:
![image](https://user-images.githubusercontent.com/20211762/39160229-04793942-4762-11e8-8200-0dfe99e97652.png)

**Comment by SimonCSmith** [comment]
I've submitted a fix for this into Master - minimise/restore will correctly size the groups tab.

It also fixes 2 related issues:
1) If you resize the main dlg to be smaller vertically than the original (default) creation size of 657x541 pixels and larger again the pictures list will be clipped.
2) If you make the dlg tall, move the splitter right up to the top, resize the dlg vertically to be very small and back tall again you will see the same issue.

Note that you don't need any lights in the list at all to see any of these issues in action.

**Comment by perdrix52** [comment]
Looks good to me from my limited testing that's another one fixed, thank you.
