### ISSUE TITLE
Save Picture to File should support 32 bit tiff

### ISSUE THREAD

**Issue by perdrix52** [LucCoiffier/DSS#29]
Both rational and integer formats.

**Comment by gzotti** [comment]
Why? Just convert the PNG (which preserves all data) to whatever format you like.

**Comment by perdrix52** [comment]
It would appear that it already does support both formats ...

**Comment by tonk777** [comment]
Yes this request can be closed. The additions appeared to be done in one of the last of the 3.x series that I never installed so was unaware.

**Comment by tonk777** [comment]
Feature is already present
