### ISSUE TITLE
Option so that autosafe.tif is saved as "uncompressed TIFF"

### ISSUE THREAD

**Issue by NGC6888** [LucCoiffier/DSS#30]
The Output of a stack process is saved as autosave.tif.
Unfortunatelly this is "compressed tiff" and it can not directly be loaded in "Astroart" for further postprocessing.

It would be nice if there is a Checkbox in "Setings" >> "Stacking Parameters" >> "Output", so that compression can be disabled or changed like in the "Save File As"-Dialog.
The Setting should be stored permanently in registry.

Thank You
Norbert

**Comment by tonk777** [comment]
Meantime:

1) Try using "Save Picture to File ..." in DSS and see if you can pick a file format that Astroart can open.

    Autosave.tiff is really only a cache/dump file in case DSS hangs/crashes etc. DSS can read it back which is its main purpose. It is a 32 bit rational (numeric floating point) format TIFF that a number of 3rd party applications cant read (DSS uses this format to preserve highest data resloution). Do we know if Astroart can read 32 rational TIFF files irrespective of compression?

2) Have you also considered contacting Astoart to request that they enhance it to be able to open standard compressed files and/or 32 bit rational TIFFs? (whichever is the real underlying problem)

**Comment by NGC6888** [comment]
Hello,
yes, I also contacted the Astroart...

So no Chance...
Ok, thank You so far.

Norbert

**Comment by tonk777** [comment]
Did you try using DSS's "Save Picture to File ..."? - there you can save 16 bit and 32 bit TIFF files in integer format. That should create a file that can be loaded into any application that claims to read TIFF files.

**Comment by NGC6888** [comment]
Hello,

now Problem now,
I use "Fitswork" to open the Autosave.tif, and then I save it without changes as *.fit (32bit integer).

As Fitswork has a Option for "vertically mirroring" Fits-Images, now I have a Picture which I can edit with "Astroart".

So no problem anymore.

**Comment by NGC6888** [comment]
Now also Astroart7 (64bit) can handle this files.
