### ISSUE TITLE
Windows XP Support

### ISSUE THREAD

**Issue by MartinDrab** [LucCoiffier/DSS#32]
Hello,

actually, this is not a real issue (maybe, sending an e-mail would be more appropriate in this case, however, I seem not to be able to find one, so I decided to create an issue.

A close relative of mine needed to run DSS on a machine with Windows XP. I decided to port DSS to thsi system and I seem to be successful so far. Code modifications related to this case are relatively insignifficant. I would create a pull request for this, however, I had to make several other changes:
* I had to do some small modifications to compile the VS solution on my machine.
* Since the system on the target machine is quite out-dated (and XP updates are no longer being shipped for XP home users, with several exceptions), I had to link DSS' executables statically because I had been unable to install necessary redistributable packages or use the runtime and MFC DLL(s). Of couse, it is not a problem to change the linking to dynamic again.
* Because of the previous point, I included sources of external libraries, such as zlib, in my DSS fork. They needed to be linked statically with the runtime too.
* I changed the structure of existing projects a bit (e.g. exporting common settings to a property sheet file, moving public headers of the libraries to an include directory global for all projects).
* I changed the platform toolset to "Visual Studio 2017 – WIndows XP".

The fork may be found on my Gihtub. If you were interested in somewhat merging my changes to your repository, I would be glad to help. I will probably make some changes, since my fork was tested in the Win32 | Release configuration settings only, however, that should be minor ones. In any case, I plan to keep the XP support as long as possible/necessary.

Martin

**Comment by perdrix52** [comment]
Just to double check - I could not locate platform toolset "Visual Studio 2017 - Windows XP" though I did find "Visual Studio 2015 - Windows XP (v140_xp)".  Is that the one you used?  If not how do I get hold of that Toolset - is it just a case of using the VS2017 Installer?

I just looked at your fork.  If you could let me know which commits actually changed code for XP that would be great.  Most seemed to be project file changes and I think I'd prefer to keep our existing project structure.

**Comment by perdrix52** [comment]
Please see my comments on the issue on Github  …

 

Thanks

David

**Comment by MartinDrab** [comment]
>  just looked at your fork. If you could let me know which commits actually changed code for XP that would be great. Most seemed to be project file changes and I think I'd prefer to keep our existing project structure.

You are right. Most of the changes are on project files and should not be necessary for the XP compatibility. I will have a look at that in a few days.

> Also is your WinXP build a non-Unicode build? I'd prefer to move forward with Unicode having just gone through that exercise!

I think it is an Unicode one.

**Comment by perdrix52** [comment]
We've discussed this a some length and have decided that we don't wish to support XP.  We of course don't object you you maintaining a fork that does.  So I'm closing this issue.
