### ISSUE TITLE
Support for additional languages (Japanese)

### ISSUE THREAD

**Issue by akanehama** [LucCoiffier/DSS#45]
I want to support Japanese. And I would like to contribute to Japanese language support.

**Comment by akanehama** [comment]
I would like to fork the source code of Master Branch and make it available in Japanese.

**Comment by perdrix52** [comment]
Sorry I didn't reply earlier - You are *most* welcome to create the necessary resource files for a Japanese translation.   I think you will need to create only a very few new files.   When you open the VS2017 sln file for DSS, you will find tranlatable files in DeepSkyStacker project under "Source Files".   I think all you should need to is to add a .rc file for the Japanese tranlation, and a Japanese flag png under "Tools",   When you have compeleted the work please  make a pull request for us to merge the changes back.

**Comment by perdrix52** [comment]
Close as no action taken by OP
