### ISSUE TITLE
Comet stacking ignoring comet position

### ISSUE THREAD

**Issue by Stim3on** [LucCoiffier/DSS#53]
I'm trying to stack images using the comet stacking function. I marked the comet in all frames, and tried both stacking methods, but DSS (4.1.1 / 64 bit) ignores that and aligns the Stars.

![image](https://user-images.githubusercontent.com/32999741/49903095-499dd580-fe66-11e8-98e8-5f650e9ea052.png)

![image](https://user-images.githubusercontent.com/32999741/49904499-a7ccb780-fe6a-11e8-8168-9dd668739c92.png)

After that  stacked the frames with DSS (3.3.2 / 32 bit) and the same settings and it worked:

![image](https://user-images.githubusercontent.com/32999741/49903210-bb761f00-fe66-11e8-8c6c-652355438546.png)

**Comment by perdrix52** [comment]
Go to the first image (in the time sequence) and carefully mark the comet position (we are still using DSS here). Repeat this with the last image in the time sequence. Now chose the reference frame - usually this should be the frame with the highest score but equally you could choose it based on the framing you want (i.e. position the comet well with respect to the frame edges - possibly aiming for rule of thirds) - and mark the comet in this frame as well. To recap you mark the comet position in just three frames of the stack - not all frames.

See also:

<https://groups.io/g/DeepSkyStacker/message/21585>

David
David
