### ISSUE TITLE
Error reading RAW files from new Sony cameras

### ISSUE THREAD

**Issue by honksys** [LucCoiffier/DSS#54]
DSS has problems reading RAW files from new Sony cameras like A99ii. Images are striped and contain rather random looking pixels.
Here is a 100% view from DSS:
![grafik](https://user-images.githubusercontent.com/45971693/50159930-45dfd800-02d8-11e9-83b0-5958ba834df4.png)
May provide full raw image (80MB) on demand.

**Comment by perdrix52** [comment]
This won't be fixed until Luc completes the integration of libraw to replace dcraw.

I don't know how long that will be

**Comment by perdrix52** [comment]
I just released 4.2.0 Beta 1 - try that
