### ISSUE TITLE
Bug in file lists: Deep sky stacker can not have same dark or bias files in several groups

### ISSUE THREAD

**Issue by Hansi123456789** [LucCoiffier/DSS#55]
Hi there,
I have a dso object photographed with two different gain values (this corresponds to different iso settings) but the same exposures with a monochrome camera in LRGB.
This means I must use several groups, say Gain1 Luminance, Gain 2 Luminance, Gain 1 Red, Gain 2 Red and so on...
Now it is clear that I need two different sets of dark files for this, namely a set of darks for gain 1 and a different set of darks for gain 2. 

And here the problem arises: If I put all darks into the main group, dss will stack them all together as it does only recognize different exposures but not different isos...

So the obvious way would be to use the dark 1 set in the Luminance gain 1 group and the dark 2 set in the luminance 2 group. 

Unfortunately, once I have added the dark 1 set in the luminance gain 1 group, I can not add the same darks into the red gain 1 group again.

Apparently, DSS accepts the same file only either in one group only or in the main group where it is then used with all files...

This is some stupid bug.... please can you fix this?
Apparently, this was done to prevent users to add the same lights for multiple times into several groups. This may be reasonable but it should not prevent you to add the same dark and bias files into several different groups

**Comment by perdrix52** [comment]
Of course you can't use the same darks in groups with different gains set. 

If you have a set of lights taken with gain 1 then you need a matching set of darks taken with gain 1, both would go in one group (not the main group),

If you also want to process another set of lights taken with gain 2, then you need a different set of darks also taken with gain 2 and these would go in another group.  

This sort of thing should be talked about on the DeepSkyStacker group at groups.io before you create an issue here (which you shouldn't have done because it's not a bug).

**Comment by perdrix52** [comment]
No actually it's not a bug - it's a **limitation** of DSS which was designed to process the output of One Shot Colour cameras. and is not designed to process LRGB.   Tony Cook is currtently thinking about how to add support for LRGB and Narrow Band but that's going to take a while.

In the meantime, I suggest that you process as follows:

L G1, Dark G1
R G1
G B1
B B1

to create one stack

and L G2, Dark G2
R G2
G G2
B G2

and then merge in PS or Gimp.
David

**Comment by tonk777** [comment]
... or duplicate the calibration files and add the duplicates to the other groups.

OK this limitation is noted for future LRGB/NB workflows. I wont be able to start on this until around April

Tony
________________________________

**Comment by Hansi123456789** [comment]
In fact, even in an LRGB workflow stacking L R G B together would, in my opinion make not much sense since the L are already there. I personally just wanted to have all files in the dss ui and then select them later easily for stacking...

However, some people really create synthetic luminances with R,G and B channels. They stack all the R,G,B files together in order to get a monochrome luminance for better S/N ratios during color combination.

https://www.cloudynights.com/topic/510027-pixinsight-synthetic-luminance-question/

So in that case, if one has two sets of R G B monochrome channels with different gains and wants to create a synthetic luminance, one should be allowed to add the same bias and dark files into several groups....

The point is that adding a single dark or bias file into several groups is not complicated for a programmer implement.

DSS just needs not to do a check more precisely. 

Currently, DSS checks that no file appears twice in the list. This check must simply be changed such that DSS checks tests whether darks or bias or flats do not appear twice in a single group...

There is actually not much image processing involved in this, it is just a filename check that has to be changed....

**Comment by Hansi123456789** [comment]
LRGB/NB workflows are quite hard by the way...

If you are interested in the mathematics for NB RGB combination:

Even Pixinsight has some problems with that. Its main ui features a quite lousy script...

Recently I had some success with this pixinsight plugin "emission line integration" from an astronomer:
http://www.skypixels.at/pixinsight_scripts.html

http://www.skypixels.at/downloads/PixInsight/scripts/EmissionLineIntegration/EmissionLineIntegration.pdf

That script does the job of enhancing the color and luminance channel of LRGB data with narrowband quite good... (Color does not suffice

So you may simply copy the math from there...
